import { RagTestDetail } from "@/lib/api/rag-exams";

export const DEMO_TEST_DATA: RagTestDetail = {
  id: "demo",
  title: "Đề thi mẫu - Kiểm tra kiến thức AI",
  description: "Đây là đề thi mẫu để test giao diện AI Editor. Bạn có thể chỉnh sửa và xem cách hiển thị của các câu hỏi.",
  num_questions: 5,
  duration_minutes: 60,
  total_score: 100,
  created_at: new Date().toISOString(),
  is_published: false,
  mode: "exam",
  max_attempts: 3,
  user_attempt_count: 0,
  questions: [
    {
      id: "demo-q1",
      content: "Trong machine learning, thuật toán nào được sử dụng phổ biến nhất để phân loại dữ liệu không tuyến tính?",
      options: [
        "Linear Regression",
        "Support Vector Machine (SVM) với kernel",
        "Logistic Regression",
        "K-Means Clustering",
      ],
      correct_answer: "B",
      explanation: "SVM với kernel (như RBF) có khả năng xử lý dữ liệu không tuyến tính bằng cách ánh xạ dữ liệu lên không gian chiều cao hơn.",
      score: 20,
      order: 1,
    },
    {
      id: "demo-q2",
      content: "Neural Network là gì và tại sao nó được sử dụng trong Deep Learning?",
      options: [
        "Là một thuật toán đơn giản không cần dữ liệu",
        "Là mạng các neuron nhân tạo mô phỏng não bộ, có khả năng học các mẫu phức tạp",
        "Chỉ dùng để xử lý văn bản",
        "Là một công cụ thống kê cơ bản",
      ],
      correct_answer: "B",
      explanation: "Neural Network là kiến trúc mô phỏng cách hoạt động của não bộ, cho phép học các mẫu phức tạp và trừu tượng từ dữ liệu lớn.",
      score: 20,
      order: 2,
    },
    {
      id: "demo-q3",
      content: "Overfitting trong machine learning xảy ra khi nào?",
      options: [
        "Mô hình học quá tốt trên dữ liệu training nhưng kém trên dữ liệu mới",
        "Mô hình học không đủ dữ liệu",
        "Mô hình không bao giờ hội tụ",
        "Mô hình luôn cho kết quả chính xác 100%",
      ],
      correct_answer: "A",
      explanation: "Overfitting xảy ra khi mô hình ghi nhớ chi tiết của dữ liệu training thay vì học các mẫu tổng quát, dẫn đến hiệu suất kém trên dữ liệu mới.",
      score: 20,
      order: 3,
    },
    {
      id: "demo-q4",
      content: "Gradient Descent là gì và vai trò của nó trong việc training mô hình?",
      options: [
        "Là phương pháp tìm kiếm ngẫu nhiên",
        "Là thuật toán tối ưu hóa để tìm giá trị tối thiểu của hàm loss bằng cách cập nhật tham số theo hướng gradient",
        "Chỉ dùng để vẽ đồ thị",
        "Là một loại activation function",
      ],
      correct_answer: "B",
      explanation: "Gradient Descent là thuật toán cốt lõi để huấn luyện mô hình, cập nhật các tham số theo hướng giảm dần của hàm loss để tìm điểm tối ưu.",
      score: 20,
      order: 4,
    },
    {
      id: "demo-q5",
      content: "Transformer architecture trong NLP có đặc điểm nổi bật nào?",
      options: [
        "Chỉ sử dụng CNN layers",
        "Sử dụng cơ chế Attention và cho phép xử lý song song, hiệu quả hơn RNN",
        "Không thể xử lý sequence dài",
        "Chỉ hoạt động với dữ liệu hình ảnh",
      ],
      correct_answer: "B",
      explanation: "Transformer sử dụng cơ chế Self-Attention cho phép mô hình tập trung vào các phần quan trọng của input, và có thể xử lý song song thay vì tuần tự như RNN.",
      score: 20,
      order: 5,
    },
  ],
};
